Dev
JianingYao/hiperglm pull request #1
Opened 2023-02-23 04:17 UTC by JianingYao

2023-02-24 18:19 UTC, chinandrew requested changes
-0 For EX1
-0 For EX2A
-0 For EX2B

Also you need to fix your DESCRIPTION file, the author field needs either an additional comma after your last name or some keyword arguments so it parses right. If you run R CMD check you'll see the issue.

2023-02-24 18:19 UTC, chinandrew commented on tests/testthat/test-are-all-close.R
> +test_that("all-are-close returns TRUE when inputs are close", {
-1

Use the correct function name in the test description, `all_are_close`. Similarly, change the filename to be consistent.

2023-02-24 18:19 UTC, chinandrew commented on tests/testthat/test-mle_func.R
> +source("./R/lm_mle_BFGS.R")
```suggestion
```

You shouldn't need this line, the files in this should get loaded when you run devtools::test().

2023-02-24 18:19 UTC, chinandrew commented on tests/testthat/test-mle_func.R
> +  x1=rnorm(100,50,9)
-1 

If possible, don't use complex test cases. Use something simple that is as easily verifiable as possible. Even a 2x2 matrix that you make up works for now. If you have to debug this, it's much harder to figure out what's going if `x1 = rnorm (100,50,9)` compared to `x1= c(1,2)`

If you do want to test a bunch of cases and want to generate random sizes that's also ok, but I'd add them as a additional test cases, and always remember to set the seed as you've done.

2023-02-24 18:19 UTC, chinandrew commented on tests/testthat/test-mle_func.R
> +  #Generate the independent variable and the error
-1

Keep comments consistent, and don't use them for describing what is being done, since that should usually be evident by reading the code. Use comments to describe why something is done.

2023-02-24 18:19 UTC, chinandrew commented on tests/testthat/test-mle_func.R
> +  beta = rnorm(3)
Using fixed test cases will also prevent you from having to keep including this block over and over again.

2023-02-24 18:19 UTC, chinandrew commented on tests/testthat/test-mle_func.R
> +test_that("return TRUE if analytical and numerical gradient match", {
-8

This and the following 2 tests are failing, please make sure they pass.

2023-02-24 18:19 UTC, chinandrew commented on tests/testthat/test-are-all-close.R
> +  v <- rep(100, 100)
Same as a comment below, you dont need to use some huge vector to test these, even c(100,100) works. Though in this case a 100-lenght vector of 100 is pretty simple, so not a big deal.

2023-02-24 18:19 UTC, chinandrew commented on R/model_output.R
> +  # warning("The function is yet to be implemented.")
-1 

Try not to leave commented out code lying around to keep things clean. If you need it again, use your git history to get it.

2023-02-24 18:19 UTC, chinandrew commented on R/hiper_glm.R
> +    if (method == "pinv") {
Don't mix single and double quotes. Tidyverse style guide recommends double quotes. Same elsewhere in code.

2023-02-24 18:19 UTC, chinandrew commented on R/lm_mle_BFGS.R
> +  loglik = - (1/(2*noise_var))*sum((y - est)^2)
-1

`y` is not defined anywhere here, perhaps you meant `outcome`?

2023-02-24 18:19 UTC, chinandrew commented on R/lm_mle_BFGS.R
> +# calculate log-likelihood under a linear model
For consistency, I'd use roxygen style function comments everywhere, even if you're not exporting them.

2023-02-24 18:19 UTC, chinandrew commented on R/hiper_glm.R
> +    }
Good job moving each mle solver into their own function, good design here.

2023-02-24 18:19 UTC, chinandrew commented on R/hiper_glm.R
> +    warning("The function is yet to be implemented.")
-1

In this case you'd want to raise an error, not a warning. 

Also in general try to make warning/error messages more specific.  E.g. if I see this, I don't know if it's because i specified an invalid model, or an invalid method.

2023-02-24 18:19 UTC, chinandrew commented on R/lm_mle_BFGS.R
> +  # loglik = -(n/2)*log(2*pi*noise_var) - (1/(2*noise_var))*sum((y - est)^2)
```suggestion
```

Like mentioned elsewhere, don't leave comments in if not used

2023-02-24 18:19 UTC, chinandrew commented on .Rhistory
> -hiper_glm()
-1

This file should be gitignored.

2023-02-24 18:19 UTC, chinandrew commented on R/lm_mle_pinv.R
> +  # use Cholesky decomposition to perform pseudo-inverse
Be consistent with function documentation, i.e. put comments above the function like you were doing earlier

2023-02-24 18:19 UTC, chinandrew commented on R/lm_mle_BFGS.R
> +approx_grad <- function(func, x, dx = .Machine$double.eps^(1/3)) {
-1

Since this is used as a testing helper, I'd move this to helper.R in the test files and not leave it here.

2023-02-24 18:19 UTC, chinandrew commented on tests/testthat/test-mle_func.R
> +  expect_true(are_all_close(lm_mle_BFGS(design, outcome, noise_var = 0.1), truth, abs_tol = 0.1, rel_tol = 0.1))
This tolerances seem a little loose, you should be able to bring these down if you wanted

2023-02-24 19:13 UTC, chinandrew commented on R/hiper_glm.R
>    supported_model <- c('linear', 'logit')
```suggestion
  supported_model <- c("linear")
```

2023-03-02 21:10 UTC, JianingYao commented on tests/testthat/test-are-all-close.R
> +test_that("all-are-close returns TRUE when inputs are close", {
fixed

2023-03-03 01:55 UTC, merged

2023-03-06 16:01 UTC, chinandrew commented
Final grade 100/100

-0 For EX1.
-0 For EX2A.
-0 For EX2B.
-0 For EX3.